# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: 'aspnetcoreapp/aspnetcoreapp.csproj'
    feedsToUse: 'select'
    includeNuGetOrg: false

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    projects: 'aspnetcoreapp/aspnetcoreapp.csproj'
- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: 'test'
    projects: 'aspnetcoreapp/aspnetcoreapp.csproj'

- task: Docker@2
  displayName: 'build and push Docker image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    repository: 'Docker Hub'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    imageName: '$(ImageName)'
    includeLatestTag: true
    useDefaultContext: false
    buildContext: '.'
- task: Docker@1
  displayName: 'Push the Docker image to Dockerhub'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'Docker Hub'
    command: Push an image
    imageName: '$(ImageName)'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  

