name: .NET

on:
  pull_request:
    branches: [ "staging" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore aspnetcoreapp/aspnetcoreapp.csproj
    - name: Build
      run: dotnet build aspnetcoreapp/aspnetcoreapp.csproj --no-restore
    - uses: actions/upload-artifact@staging
      with:
        name: webpack artifacts
        path: public/
    # - name: Test
    #   run: dotnet test aspnetcoreapp/aspnetcoreapp.csproj --no-build --verbosity normal
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/donwload-artifact@staging
        with:
          name: webpack artifacts 
          path: public
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x 
      - name: Restore dependencies
        run: dotnet restore aspnetcoreapp/aspnetcoreapp.csproj
      - name: Test
        run: dotnet test aspnetcoreapp/aspnetcoreapp.csproj --no-build --verbosity normal
